<?php

namespace App\Models\Enums;

enum GenAIRequestStateOld : int
{
    case INTERNAL_GEN_AI_REQ_STATE_0_INIT = 0;
    case INTERNAL_GEN_AI_REQ_STATE_1_TRX_ID_PARSED = 1;
    case INTERNAL_GEN_AI_REQ_STATE_2_RETRIEVED_TRX_DATA = 2;
    case INTERNAL_GEN_AI_REQ_STATE_3_JOB_SET_AS_AI = 3;
    case INTERNAL_GEN_AI_REQ_STATE_4_AI_JOB_SET_AS_NEW = 4;
    case INTERNAL_GEN_AI_REQ_STATE_5_DOWNLOADED_TRX_AUDIO = 5;
    case INTERNAL_GEN_AI_REQ_STATE_6_UPLOADED_TRX_AUDIO = 6;
    case INTERNAL_GEN_AI_REQ_STATE_7_UPDATED_JOB_BODY = 7;
    case INTERNAL_GEN_AI_REQ_STATE_8_AI_JOB_SET_AS_READY = 8;
}
